autoInstallPeers: true

enablePrePostScripts: true

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - keccak
  - sharp
  - utf-8-validate
  - workerd

preferSymlinkedExecutables: true

saveExact: true

strictPeerDependencies: false
