packages:
  - packages/*
  - apps/*

autoInstallPeers: true

enablePrePostScripts: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

preferSymlinkedExecutables: true

saveExact: true

strictPeerDependencies: true
