// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: c128efe88a3bb47ef54176ba197680dd)
interface Env {
	KV: KVNamespace;
	WARPCAST_BASE_URL: string;
	NOUNS_SUBGRAPH_URL: string;
	NEYNAR_API_URL: string;
	LOG_LEVEL: string;
	PROPOSAL_BASE_URL: string;
	WARPCAST_ACCESS_TOKEN: string;
	WARPCAST_API_KEY: string;
	ALCHEMY_API_KEY: string;
	NEYNAR_API_KEY: string;
	NODE_ENV: string;
	QUEUE: Queue;
}
