/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: d74a527f5ce9b38345df41ce98513e20)
declare namespace Cloudflare {
	interface Env {
		KV: KVNamespace;
		WARPCAST_BASE_URL: string;
		NOUNS_SUBGRAPH_URL: string;
		NEYNAR_API_URL: string;
		LOG_LEVEL: string;
		PROPOSAL_BASE_URL: string;
		WARPCAST_ACCESS_TOKEN: string;
		WARPCAST_API_KEY: string;
		ALCHEMY_API_KEY: string;
		NEYNAR_API_KEY: string;
		NODE_ENV: string;
		ALCHEMY_SIGNING_KEY: string;
		QUEUE: Queue;
	}
}
interface Env extends Cloudflare.Env {}
